### PR TITLE
Asynchronous_to_result_api.py

### PR DESCRIPTION
**Pull request by smog-root**
**Issue_id**: #3

**Usage:**

You can call the bulkresults function with the required parameters, and it will now fetch results asynchronously. For example:

```
# In your main script
import asyncio

async def main():
    results = await bulkresults("path_to_file.csv", "main", 1, 1)
    print(results)

if __name__ == "__main__":
    asyncio.run(main())
```

_**Note:-**_ Add all labels added to issue #3 to this PR. So that GSSoC team can easily recognize the commit!

### CODE REVIEW

**Comment by cro2003** [comment]
Did you tested your Code?

**Comment by smog-root** [comment]
> Did you tested your Code?

yes! @cro2003. you can merge it!

**Comment by cro2003** [comment]
I just tested and its showing error.

**Comment by smog-root** [comment]
> I just tested and its showing error.

send a screenshot!!

**Comment by cro2003** [comment]
```
Traceback (most recent call last):
  File "/Users/cro/Library/Mobile Documents/com~apple~CloudDocs/Projects/Packages/rgpvApi/test.py", line 9, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cro/Library/Mobile Documents/com~apple~CloudDocs/Projects/Packages/rgpvApi/test.py", line 5, in main
    results = await rgpvApi.bulkresults("input.csv", "main", 24, 4)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cro/Library/Mobile Documents/com~apple~CloudDocs/Projects/Packages/rgpvApi/package_test.py", line 186, in bulkresults
    results_data = await asyncio.gather(*tasks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cro/Library/Mobile Documents/com~apple~CloudDocs/Projects/Packages/rgpvApi/package_test.py", line 162, in fetch_result
    fetched_result = await stu_result.getMain(sem)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cro/Library/Mobile Documents/com~apple~CloudDocs/Projects/Packages/rgpvApi/package_test.py", line 35, in getMain
    return await self.__parse_main_result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cro/Library/Mobile Documents/com~apple~CloudDocs/Projects/Packages/rgpvApi/package_test.py", line 73, in __parse_main_result
    "name": " ".join(self.soup.find(id='ctl00_ContentPlaceHolder1_lblNameGrading').get_text().split()),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_text'

```

**Comment by smog-root** [comment]
use python 3.12!

**Comment by cro2003** [comment]
its the same error.

**Comment by smog-root** [comment]
just close the PR and the issue. i can't do it anymore! @cro2003

**Pull request closed without merging**
