### PR TITLE
Added csv bulk result feature

### LINKED ISSUE #4: Implement CSV Functionality for Fetching Examination Results
[Function Idea] Implementation of a function that allows users to fetch examination results in bulk using a CSV file containing enrollment IDs at once and receive their corresponding results in a structured CSV or JSON format.
Proposed Functionality:
Input CSV Format: The input CSV should contain a single column labeled enrolment_id with enrollment numbers of the students.
Output (for eg. if CSV Format):
The output CSV can include the following columns:
enrolment_id, name, status (e.g., PASS/FAIL/PASS WITH GRACE), sgpa ,cgpa, subjects (a formatted json of subjects with their respective grades), etc
Implementation Details:
Can use the existing methods from the rgpvApi.result to fetch results (getMain, getReval, getChlng) by allowing users to specify the type of results they wish to fetch (Main, Revaluation, Challenge) along with course ID and semester.
This functionality will provide a more streamlined and efficient way for users to access examination results for multiple students without needing to make individual requests. (especially for institutes willing to download results of all their students)
I would like to request to be assigned this issue, I am eager to contribute to this feature under gssoc-ext and hacktoberfest-accepted. Would love to have any suggestions or amendments in the idea from your side as well.

### PR DESCRIPTION
**Pull request by Himanshi-m**
Closes #4 
Hi, My name is Himanshi Maheshwari, a gssoc-extd contributer on github as @Himanshi-M

Introduced a new static method, csvresults, in the rgpvAPI. This method allows users to fetch examination results for multiple enrollment IDs from a specified CSV file. Results can be of three types: "Main" Result, "Revaluation" Result, and "Challenge" Result, returned in a structured JSON format.

Changes Made:
Added Static Method: csvresults
- Accepts the path of a CSV file containing enrollment IDs, a course ID, a result type, and a semester.
- Reads enrollment IDs from the CSV file and fetches the corresponding examination results using the existing methods (getMain, getReval, and getChlng).
- Converts results from JSON string format into Python dictionaries for structured handling.

Structured JSON Output
- Outputs a JSON object with enrollment IDs as keys and their respective result data, enabling easier access and manipulation.

✅Performed checks and tested with a csv input as a testcase, verified output.

### CODE REVIEW

**Comment by cro2003** [comment]
Looking great, just please add this functionality in `result_api.py` file.

**Comment by Himanshi-m** [comment]
Alright on it

**Comment by Himanshi-m** [comment]
Done. The function can now be called as rgpvApi.result_api.csvresults()
Please review @cro2003

**Comment by cro2003** [comment]
Looks Great

**Comment by Himanshi-m** [comment]
Hey, @cro2003 please add the labels here as well. Thank you so much.

**Comment by Himanshi-m** [comment]
Hey, the label should be gssoc-ext not gssoc-extd please check and fix that.

**Comment by cro2003** [comment]
Done

**Pull request merged**
