### PR TITLE
Enhanced csvresults function

### LINKED ISSUE #10: Add more features to csvresults function
Hi, I want to generalize the csvresults function to be able to read data from both csv and excel files
and as the csv reader function reads rows one by one, I want to make it fast such that it fetches multiple results in parallel. 

 I'm currently working on GSSoC Extended. Please assign me the labels.

@cro2003

### PR DESCRIPTION
**Pull request by PavanTeja2005**
Fix #10 
Generalized csvresults function's file open ability to be able to read both csv and excel files.
Renamed csvresult function to bulkresults function.
Added concurrent processing using 2 threads.

### CODE REVIEW

**Comment by cro2003** [comment]
I guess you forgot to add `import concurrent.futures`

**Comment by PavanTeja2005** [comment]
It got deleted by mistake after testing. I have added it and finalised everything.

Here are the test results.
image

and the output.

image

**Comment by cro2003** [comment]
Remove ts.csv and tse.xlsx

**Comment by PavanTeja2005** [comment]
I have removed those files

**Pull request merged**
