### PR TITLE
feat: Add RGPV Results Fetcher with SQLite Disk Caching System

### LINKED ISSUE #32: Adding Caching
Cache certain API responses to reduce API requests (e.g., student information, course catalog, common results).

(I want to work on this issue)

### PR DESCRIPTION
**Pull request by anishka25**
This PR introduces a result fetching system with an integrated SQLite caching mechanism. The implementation supports fetching cached main semester results, revaluation results, and challenge examination results, with both single-student and bulk processing capabilities.

Technical Implementation

Caching System:

Uses SQLite for persistent storage
Configurable cache duration (default: 24 hours)
Automatic cache invalidation

Fixes #32

### CODE REVIEW

**Comment by anishka25** [comment]
@cro2003 Please check

**Comment by cro2003** [comment]
Hey So Sorry to keep you waiting, but I will surely review it within 48 hours

**Comment by anishka25** [comment]
@cro2003 Hey any updates?

**Comment by anishka25** [comment]
@cro2003 Hey tomorrow is the last day can you quickly review it it would be really really great!

**Comment by cro2003** [comment]
Hey So Sorry I was busy, i have reviewed the Code and merging it right now.

**Pull request merged**
